auto: false 

title: "Learn All The Things"

permalinks: pretty
pygments: true

exclude: deploy.sh

author:
  name: Simon Goudie
  email: simon@simongoudie.com
  github: simongoudie
  twitter: simongoudie

name: "Learn All The Thing"
description: "Simon Goudie's Blog"
url: http://simon4.com
