auto: false 

title: "Learn All The Things"

permalinks: pretty
pygments: true

exclude: deploy.sh deployloc.sh newpost.sh

author:
  name: Simon Goudie
  email: simon@simongoudie.com
  github: simongoudie
  twitter: simongoudie

name: "Learn All The Thing"
description: "Simon Goudie's Blog"
#Uncomment for production:
#url: http://simongoudie.com/blog
#Uncomment for testing:
#url: http://goudz.com/blog
url: http://simon4.com/blog
#Uncomment for local testing:
#url: http://192.168.1.16/blog
