auto: false 

name: "Learn All The Thing"
description: "Simon Goudie's Blog"
title: "Learn All The Things"

permalinks: pretty
pygments: true

exclude: deployproduction.sh deploylocal.sh newpost.sh

author:
  name: Simon Goudie
  email: simon@simongoudie.com
  github: simongoudie
  twitter: simongoudie

#Details for deploying via glynn
ftp_host: simongoudie.com
ftp_dir: /public_html/simongoudie/blog

#URL for production
#rl: http://simongoudie.com/blog
